version: 1
disable_existing_loggers: false

formatters:
  colored:
    "()": colorlog.ColoredFormatter
    format: "[%(yellow)s%(asctime)s%(reset)s] [%(blue)s%(name)s%(reset)s] [%(log_color)s%(levelname)s%(reset)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    log_colors:
      DEBUG: cyan
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: bold_red

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout

loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: false

  uvicorn.error:
    level: INFO
    handlers: [console]
    propagate: false

  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console]